### ISSUE TITLE
RuntimeError: can't add a new key into hash during iteration with Ruby 3.1

### ISSUE THREAD

**Issue by mildred** [fxn/zeitwerk#207] opened 2022-01-24 08:46 UTC
On a rails 7.0.1 project (converted from earlier versions) with ruby 3.1.0, I sometimes get the following error on the dev setup:

```
RuntimeError: can't add a new key into hash during iteration
zeitwerk (2.5.3) lib/zeitwerk/loader.rb:438:in `set_autoload'
zeitwerk (2.5.3) lib/zeitwerk/loader.rb:408:in `autoload_file'
zeitwerk (2.5.3) lib/zeitwerk/loader.rb:334:in `block in set_autoloads_in_dir'
zeitwerk (2.5.3) lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
zeitwerk (2.5.3) lib/zeitwerk/loader/helpers.rb:18:in `each_child'
zeitwerk (2.5.3) lib/zeitwerk/loader/helpers.rb:18:in `ls'
zeitwerk (2.5.3) lib/zeitwerk/loader.rb:329:in `set_autoloads_in_dir'
zeitwerk (2.5.3) lib/zeitwerk/loader/callbacks.rb:76:in `block in on_namespace_loaded'
zeitwerk (2.5.3) lib/zeitwerk/loader/callbacks.rb:75:in `each'
zeitwerk (2.5.3) lib/zeitwerk/loader/callbacks.rb:75:in `on_namespace_loaded'
zeitwerk (2.5.3) lib/zeitwerk/loader/callbacks.rb:60:in `block in on_dir_autoloaded'
zeitwerk (2.5.3) lib/zeitwerk/loader/callbacks.rb:46:in `synchronize'
zeitwerk (2.5.3) lib/zeitwerk/loader/callbacks.rb:46:in `on_dir_autoloaded'
zeitwerk (2.5.3) lib/zeitwerk/kernel.rb:31:in `require'
activesupport (7.0.1) lib/active_support/inflector/methods.rb:280:in `const_get'
activesupport (7.0.1) lib/active_support/inflector/methods.rb:280:in `constantize'
activesupport (7.0.1) lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
actionpack (7.0.1) lib/action_dispatch/http/request.rb:90:in `controller_class_for'
actionpack (7.0.1) lib/action_dispatch/request/utils.rb:95:in `action_encoding_template'
actionpack (7.0.1) lib/action_dispatch/request/utils.rb:83:in `encode'
actionpack (7.0.1) lib/action_dispatch/request/utils.rb:45:in `set_binary_encoding'
actionpack (7.0.1) lib/action_dispatch/http/parameters.rb:68:in `path_parameters='
actionpack (7.0.1) lib/action_dispatch/journey/router.rb:48:in `block in serve'
actionpack (7.0.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:850:in `call'
omniauth (2.0.4) lib/omniauth/strategy.rb:470:in `call_app!'
omniauth_openid_connect (efdfe76369c5) lib/omniauth/strategies/openid_connect.rb:146:in `other_phase'
omniauth (2.0.4) lib/omniauth/strategy.rb:195:in `call!'
omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
bullet (7.0.0) lib/bullet/rack.rb:12:in `call'
i18n-js (3.9.0) lib/i18n/js/middleware.rb:14:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (7.0.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (7.0.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/cookies.rb:693:in `call'
activerecord (7.0.1) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.1) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
sentry-rails (4.9.0) lib/sentry/rails/rescued_exception_interceptor.rb:9:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
sentry-ruby-core (4.9.0) lib/sentry/rack/capture_exceptions.rb:11:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (7.0.1) lib/rails/rack/logger.rb:27:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
rack-mini-profiler (2.3.3) lib/mini_profiler/profiler.rb:393:in `call'
railties (7.0.1) lib/rails/engine.rb:530:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/lint.rb:50:in `_call'
config/initializers/rack_lint_websocket.rb:14:in `_call'
rack (2.2.3) lib/rack/lint.rb:38:in `call'
rack (2.2.3) lib/rack/show_exceptions.rb:23:in `call'
rack (2.2.3) lib/rack/common_logger.rb:38:in `call'
rack (2.2.3) lib/rack/content_length.rb:17:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread' 
```

I noticed that the constant does not autoload and it can cause issues later on, solved only by restarting the server.

**Comment by mildred** [comment] 2022-01-24 08:52
A similar stack trace (that I encunter more often) with `on_file_autoloaded` instead of `on_dir_autoloaded`:

```
zeitwerk (2.5.3) lib/zeitwerk/loader/callbacks.rb:18:in `on_file_autoloaded'
zeitwerk (2.5.3) lib/zeitwerk/kernel.rb:28:in `require'
app/controllers/application_controller.rb:61:in `set_debug'
activesupport (7.0.1) lib/active_support/callbacks.rb:400:in `block in make_lambda'
activesupport (7.0.1) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
actionpack (7.0.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (7.0.1) lib/active_support/callbacks.rb:200:in `block in halting'
activesupport (7.0.1) lib/active_support/callbacks.rb:595:in `block in invoke_before'
activesupport (7.0.1) lib/active_support/callbacks.rb:595:in `each'
activesupport (7.0.1) lib/active_support/callbacks.rb:595:in `invoke_before'
activesupport (7.0.1) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
actiontext (7.0.1) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.1) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.1) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.1) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.1) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.1) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.1) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.1) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.1) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.1) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.1) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.1) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.1) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.1) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.1) lib/action_dispatch/routing/route_set.rb:850:in `call'
omniauth (2.0.4) lib/omniauth/strategy.rb:470:in `call_app!'
omniauth_openid_connect (efdfe76369c5) lib/omniauth/strategies/openid_connect.rb:146:in `other_phase'
omniauth (2.0.4) lib/omniauth/strategy.rb:195:in `call!'
omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
bullet (7.0.0) lib/bullet/rack.rb:12:in `call'
i18n-js (3.9.0) lib/i18n/js/middleware.rb:14:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (7.0.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (7.0.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/cookies.rb:693:in `call'
activerecord (7.0.1) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.1) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
sentry-rails (4.9.0) lib/sentry/rails/rescued_exception_interceptor.rb:9:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
sentry-ruby-core (4.9.0) lib/sentry/rack/capture_exceptions.rb:11:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (7.0.1) lib/rails/rack/logger.rb:27:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.1) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
rack-mini-profiler (2.3.3) lib/mini_profiler/profiler.rb:393:in `call'
railties (7.0.1) lib/rails/engine.rb:530:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/lint.rb:50:in `_call'
config/initializers/rack_lint_websocket.rb:14:in `_call'
rack (2.2.3) lib/rack/lint.rb:38:in `call'
rack (2.2.3) lib/rack/show_exceptions.rb:23:in `call'
rack (2.2.3) lib/rack/common_logger.rb:38:in `call'
rack (2.2.3) lib/rack/content_length.rb:17:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread' 
```

**Comment by mildred** [comment] 2022-01-24 09:09
I don't see in the stack traces where the iteration happens, but grepping at the code it seems that the only place is in lib/zeitwerk/loader.rb lines 134 and 146

**Comment by fxn** [comment] 2022-01-24 17:03
This is weird, first time I see it.

Do you have a way to reproduce? If it is not deterministic, could you please enabled logging by throwing

```ruby
Rails.autoloaders.log!
```

in `config/application.rb` and share the traces since the last reload? Are you issuing concurrent requests?

**Comment by fxn** [comment] 2022-01-24 21:43
As you said, for example in the second trace, you'd say that while

```ruby
to_unload[cpath] = [file, cref] if reloading_enabled?
```

is happening in the callback, there is a reloading going on at the same time. However, also as you noted, the loop is not in the backtrace.

To me, it smells to non-synchronized reloading going on in Rails. (Reloading is not thread-safe, client frameworks are responsible for coordinating reload.)

**Comment by mildred** [comment] 2022-01-26 12:02
Should I open an issue in rails ?

**Comment by fxn** [comment] 2022-01-26 12:05
@mildred yes, I think that'd be the right place. All indicates there's concurrent autoloading and reloading, and Rails is responsible for preventing that.

Thanks :).

**Comment by fxn** [comment] 2022-01-26 20:14
Thanks for opening those issues. In principle, Zeitwerk does not seem to have a bug here, so closing and following in the Rails repo.

**Closed by fxn** 2022-01-26 20:14 UTC
