### ISSUE TITLE
`TestIgnore#test_returns_true_for_a_file_in_a_descendant_of_an_ignored_directory` failed

### ISSUE THREAD

**Issue by pvalena** [fxn/zeitwerk#202] opened 2022-01-06 13:00 UTC
Hello,

while building in Fedora, we run the test suite. The following test failed for me with Ruby 3.0.3:
```
  1) Failure:
TestIgnore#test_returns_true_for_a_file_in_a_descendant_of_an_ignored_directory [/builddir/build/BUILD/zeitwerk-2.5.3/usr/share/gems/gems/zeitwerk-2.5.3/test/lib/zeitwerk/test_ignore.rb:171]:
Expected false to be truthy.
```

I'm clueless on how to debug this. Do you have any advice?

**Comment by fxn** [comment] 2022-01-06 13:17
Interesting. I'm out now, but let me ask if the failure is consistent.

**Comment by pvalena** [comment] 2022-01-06 17:00
No rush, I've disabled the test in our build system for now.

Yes, happens every time the test runs. Maybe it's due to way we run the test suite?

We run it in this way, for simplicity:
```
$ ruby -Itest:lib -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
```
We also run without minitest-reporters and minitest-focus.

**Comment by fxn** [comment] 2022-01-06 20:08
I cannot reproduce here. Could you be so kind as to edit the test and send me the output?

That would be: open `test/lib/zeitwerk/test_ignore.rb`, go to line 171, and replace

```ruby
test "returns true for a file in a descendant of an ignored directory" do
  loader.ignore(ascendant)
  assert loader.ignores?(this_file)
end
```

with

```ruby
test "returns true for a file in a descendant of an ignored directory" do
  pp loader
  pp ascendant
  pp this_file
  loader.ignore(ascendant)
  assert loader.ignores?(this_file)
end
```

and execute

```
ruby -Itest:lib test/lib/zeitwerk/test_ignore.rb
```

What does that print?

**Comment by fxn** [comment] 2022-01-09 19:50
Got Fedora under Parallels Desktop and could not reproduce either:

<img width="683" alt="Screen Shot 2022-01-09 at 20 46 21" src="https://user-images.githubusercontent.com/3387/148698193-bfd0a8a3-d53a-4d64-b9fd-8e64a4cc567f.png">

Would really help if you could share the traces detailed above, or give instructions or a server where I can debug it (my email is in my user profile here in GitHub).

**Comment by fxn** [comment] 2022-01-23 19:31
Hey! I like to have 0 issues in this repo.

I am going to close the issue because I cannot reproduce it. However, if you ever get a chance to provide more information using the snippets above, or give me shell access, ..., please do not hesitate to follow up!

**Closed by fxn** 2022-01-23 19:31 UTC
