### ISSUE TITLE
open class for override in reload case is not supported 

### ISSUE THREAD

**Issue by qinmingyuan** [fxn/zeitwerk#27] opened 2019-03-19 11:05 UTC
ruby: 2.6.2
rails: 6.0.0.beta3

I have a model  defined in my engine:
```ruby
# app/models/rails_org/member.rb
class Member < ApplicationRecord
end
```
I overrided it in my main project
```ruby
# app/models/member.rb
require 'rails_org/member'
class Member < ApplicationRecord
end
```
in reload case,  only delete main model defined path from $LOADED_FEATURES

Sorry for my poor english,  if need more information,  please point out.

**Comment by fxn** [comment] 2019-03-19 11:11
Which version of Rails are you using?

**Comment by qinmingyuan** [comment] 2019-03-19 11:13
I use rails 6.0.0beta3

**Comment by fxn** [comment] 2019-03-19 11:14
Problem here is that the engine is not following naming conventions.

A file called `app/models/rails_org/member` should define a constant called `RailsOrg::Member`, not `Member`. If it did and you used the current Rails master, all would work.

Otherwise, you have to stick with `:classic`.

**Comment by qinmingyuan** [comment] 2019-03-19 11:22
I do this purposely,  define model in engine without namespace, but with path prefix. So I can conveniently override it.

I have followed your code here:
```ruby
# zeitwerk-1.3.4/lib/zeitwerk/loader.rb @ line 222
    215: def unload
    216:   mutex.synchronize do
    217:     autoloads.each do |path, (parent, cname)|
    218:       if parent.autoload?(cname)
    219:         parent.send(:remove_const, cname)
    220:         log("autoload for #{cpath(parent, cname)} removed") if logger
    221:       elsif cdef?(parent, cname)
 => 222:         binding.pry if cname == 'Member'
    223:         parent.send(:remove_const, cname)
    224:         log("#{cpath(parent, cname)} unloaded") if logger
    225:       end
    226:
    227:       # Let Kernel#require load the same path later again by removing it
    228:       # from $LOADED_FEATURES. We check the extension to avoid unnecessary
    229:       # array lookups, since directories are not stored in $LOADED_FEATURES.
    230:       $LOADED_FEATURES.delete(path) if ruby?(path)
    231:     end
```
I'm thinking is it possible to map both path to this constant define for unload.

Do you consider this as a feature?

**Comment by fxn** [comment] 2019-03-19 11:39
> Do you consider this as a feature?

Not really.

**Comment by qinmingyuan** [comment] 2019-03-19 13:24
I know I can disable zeitwerk by set to classic mode.
I love your gem, It's awesome, that's why I'm trying to use it in my project.

I'm trying to understand your code to find out why can not add both related realpath to the constant~

In my opinion,  reopen a class for override is common use in ruby.  if you can support this,  that will be very nice.

**Comment by fxn** [comment] 2019-03-19 22:05
Basically, Zeitwerk is an autoloader based on `Module#autoload`, and that method allows you to associate _one_ file to _one_ constant, so when you set autoloads you can only have one choice.

BTW, does your code work with `:classic` if you change the application `Member` and reload? What happens if you change `ApplicationRecord` and reload?

**Comment by qinmingyuan** [comment] 2019-03-20 03:02
It works well under `:classic` mode.

I'm making a pull request try to fix this. I have tested it with this issue case;

Your works are profound,  I'm not confident if I missed something,  would you please help review my PR.

**Comment by fxn** [comment] 2019-03-20 09:25
Can you show me a minimal application where reloading works in `:classic` with that setting? You could generate an app, and a minimal engine in vendor, point the Gemfile to that engine using `path`, and upload the whole thing.

**Comment by qinmingyuan** [comment] 2019-03-20 12:10
test app:[https://github.com/qinmingyuan/test_zeitwerk](https://github.com/qinmingyuan/test_zeitwerk)

I have add my test step and fixed test step in README

**Comment by fxn** [comment] 2019-03-23 19:32
This code does not reload in `:classic`, because the `User` constant is not autoloaded.

To see it you just need to fire a console and autoload `User:

```
> User
```

Now, without closing the shell open `app/models/user.rb` in the application and add a new method

```ruby
def foo
  :foo
end
```

go back to the shell:

```
> reload!
> User.new.foo
NoMethodError
```

As a rule of thumb, `require` and classic autoloading [do not play well](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-and-require). For autoloading to work well, you need to name files and directories matching their corresponding constant paths. Deviating from that won't generally work in `:classic`.

I'd recommend to use standard object orientation, for example the engine could define an abstract `BaseUser` in `app/models/base_user.rb`, and the application would define a `User` concrete subclass. Or some other OO clean technique that fits what you want to accomplish.

This is use case certainly won't be supported by Zeitwerk either.

**Closed** 2019-03-23 19:33 UTC

**Comment by qinmingyuan** [comment] 2019-03-24 03:01
Please consider close this issue later.

First of all:
If not care about my unusual use case, just focus on the Pull Request.

```
A shadowed file is a file managed by this autoloader that is skipped
because its matching constant path has already been seen. Think $LOAD_PATH
and require, only the first occurrence of a given relative name is loaded.
```

```ruby
# If some constants has been loaded from A file, and reopened (Open Class) in B file.
# shadowed_files will map file to first autoload_path.
# repeats find them and delete all from $LOADED_FEATURES for reload.
repeats = autoloads.keys & shadowed_files.values
repeats.each do |repeat|
  shadowed_files.select { |_, v| v == repeat }.each do |path, _|
      if ruby?(path)
         $LOADED_FEATURES.delete(path)
         log("repeated #{path} removed from $LOADED_FEATURES") if logger
      end
  end
end
```
I think this patch is necessary, my reason is:
1.  A constant has been seen and opened again, will add to shadowed_files. When need reload this constant,  now `zeitwerk`(zeitwerk mode) only delete the first seen path from $LOADED_FEATURES, when fired reload, another paths related to the constant may not loaded. So will lost some method definition.

2. My patch is clearly,  just solved the issues. when delete all autoloads path from $LOADED_FEATURES,  just find if any paths stored in shadowed_files related to the same constants.then delete it from $LOADED_FEATURES,  It's safe. 

3. `zeitwerk` is designed not just for Rails application, rails application has some conventions, but not all ruby application. If codes have been followed basic ruby rule. when `zeitwerk` can easily support that. is it a good things?

My english is not very good. So my expression may be not catch your concern. please give  more attention for this issue.

Thank you very much.

**Comment by fxn** [comment] 2019-03-24 09:01
The preconditions Zeitwerk require in projects using it are not there because of Rails, but because that is how Zeitwerk is possible. Indeed, Zeitwerk demands a structure that is stricter than Rails classic.

The goal of the project is not to support any Ruby project. Ruby is very flexible, you can define 12 classes in a file called `models.rb`. You can change the constant that accesses a class object

```ruby
class C; end
X = C
Object.send(:remove_const, :C)
x = X.new
x.class.name # => C
```

Ruby is very flexible, but Zeitwerk cannot support Ruby in all its genericity, because the problem is unsolvable with this technique in all its genericity.

If you reopen something defined elsewhere and reload, the original constant is deleted and you won't be able to reload it generally. It is a rabbit hole of inconsistencies. Reopening is only supported for namespaces, and still there there is constraints.

The project constraints are there for a reason, and not all projects can use this gem.

**Comment by qinmingyuan** [comment] 2019-03-24 10:15
Thank you for the very detailed explain.

and I get new idea to refactor my engines.
